Installing Numpy

Using pip command to install numpy. Use '!' to install in notebook.

In [1]:
!pip install numpy

In [4]:
!pip install numpy -q     # -q---> if we dont want display the confirmation messages

Importing Numpy

In [3]:
import numpy as np

Numpy Operations

Numpy array is a powerful, N-dimensional grid-like data structure used for high-performance numerical computing in Python where you can multiple values of same data type.

Advantages

- Use less memory than list when storing same type.
- Faster for numeric operations
- Keep values in order
- Easy index access

Disdvantages

- Same datatype only
- Less flexible than list

- Creating Numpy Array

In [1]:
[1,2,3,4]    # Creating a List

[1, 2, 3, 4]

In [2]:
type([1,2,3,4])   # Checking the type of datatype

list

In [7]:
np.array([1,2,3,4])   # Creating a numpy array

array([1, 2, 3, 4])

In [8]:
arr1  = np.array([1,2,3,4])  # Assigning to a variable

In [9]:
[[1,2],[3,4]]   # Two dimentional lists

[[1, 2], [3, 4]]

In [10]:
arr2 = np.array([[1,2],[3,4]])   # Two dimensional arrays

In [11]:
arr2

array([[1, 2],
       [3, 4]])

- Special Arrays

In [13]:
np.zeros((2,3))   # Arrays with all elements with value zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((3,2))    # Arrays with all elements with value ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.eye(3)   # Arrays with all diagonal elements with value one

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.arange(0,10,2)   # It is similar to range function, printing from 0 to 9 with step 2

array([0, 2, 4, 6, 8])

- Array Attributes

In [18]:
arr2.shape   # Checking the shape of an array

(2, 2)

In [19]:
arr2

array([[1, 2],
       [3, 4]])

In [20]:
arr2.ndim    # Checking the array dimensions

2

In [21]:
arr1.ndim

1

In [22]:
arr1

array([1, 2, 3, 4])

In [23]:
arr2.dtype    # Checking the datatype

dtype('int64')

- Indexing and Slicing

In [24]:
arr1

array([1, 2, 3, 4])

In [25]:
arr1[1]   # Similar to list, printing the second element

np.int64(2)

In [26]:
arr2

array([[1, 2],
       [3, 4]])

In [27]:
arr2[0][1]   # Printing first row, second element

np.int64(2)

In [28]:
arr2[0]    # Printing first row

array([1, 2])

In [29]:
arr2[0][1]   # Printing first row second element

np.int64(2)

In [30]:
arr1

array([1, 2, 3, 4])

In [31]:
arr1[1:3]   # Slicing, similar to list, print 2nd and 3rd element

array([2, 3])

In [32]:
arr2

array([[1, 2],
       [3, 4]])

In [33]:
arr2[1]  # Printing second row

array([3, 4])

In [37]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])  # Creating a two dimentional array with multiple values

In [38]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 4, 6, 8]])

In [39]:
arr3.ndim

2

In [40]:
arr3[1][1:]   # Printing second row with 2nd,3rd and 4th element

array([6, 7, 8])

- Modifying Elements

In [41]:
arr1

array([1, 2, 3, 4])

In [42]:
arr1[0] = 10  # Changing the value of an array.

In [43]:
arr1

array([10,  2,  3,  4])

- Arithmatic Operations

In [44]:
arr1

array([10,  2,  3,  4])

In [45]:
arr2

array([[1, 2],
       [3, 4]])

In [4]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [5]:
a, b = np.array([1,2,3]), np.array([4,5,6])  # Alternate method to create two arrays in single line of code

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([4, 5, 6])

In [8]:
a+b    # Adding two arrays.

array([5, 7, 9])

In [10]:
[1,2,3]+[4,5,6]  # Adding two lists

[1, 2, 3, 4, 5, 6]

In [11]:
a+5    # Adding values to a array

array([6, 7, 8])

In [14]:
a*b    # Multiplying two arrays

array([ 4, 10, 18])

In [15]:
a**2   # Square the values of an array

array([1, 4, 9])

- Aggregate Functions

In [17]:
np.sum(a)    # Sum the values of an array

np.int64(6)

In [18]:
a

array([1, 2, 3])

In [19]:
np.mean(a)    # Mean value of an array

np.float64(2.0)

In [20]:
np.min(a)     # Printing the minimum value

np.int64(1)

In [21]:
np.max(a)     # Printing the maximum value

np.int64(3)

- Matrix Operations

In [22]:
m1 = np.array([[1,2],[3,4]])

In [23]:
m1

array([[1, 2],
       [3, 4]])

In [24]:
m2 = np.array([[5,6],[7,8]])
m2

array([[5, 6],
       [7, 8]])

In [25]:
np.dot(m1,m2)   # Matrix multiplication

array([[19, 22],
       [43, 50]])

Convert Temperature C to F

*Example problem to convert temperature in C to F.*

c = 0, 20, 37, 100

f = c * 9/5 + 32

In [26]:
c = np.array([0,20,37,100])
c

array([  0,  20,  37, 100])

In [27]:
c*9/5+32

array([ 32. ,  68. ,  98.6, 212. ])

In [28]:
c*(9/5)+32

array([ 32. ,  68. ,  98.6, 212. ])